spring.application.name=tranthuy
# 1. Địa chỉ kết nối (Lấy từ thanh Object Explorer của bạn)
spring.datasource.url=jdbc:sqlserver://mssql7.gear.host:1433;databaseName=itsolutions;encrypt=true;trustServerCertificate=true

# 2. Tài khoản đăng nhập (Theo ảnh database users của bạn)
spring.datasource.username=itsolutions
spring.datasource.password=@Thanhthuy231205

# 3. Các cấu hình JPA và Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect
spring.thymeleaf.cache=false

server.port=${PORT:8080}
